name: CI/CD pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  
jobs:
  build-and-deploy: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v2.1.0
        with:
         dotnet-version: 6.0.x
       
      - name: Restore dependencies
        run: dotnet restore
    
      - name: Build
        run: dotnet build -c Release --no-restore
    
      - name: Test
        run: dotnet test -c Release --no-restore --no-build
        
      - name: Publish
        run: dotnet publish

      - name: Upload API Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: back-app
          path: bin/Debug/net6.0/publish/
    
      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - uses: azure/docker-login@v1
        with:
          login-server: bankapphenn.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - run: |
          docker build ./src/BankAccountApi/ --file Dockerfile -t bankapphenn.azurecr.io/myapp:${{ github.sha }}
          docker push bankapphenn.azurecr.io/myapp:${{ github.sha }}     
      
      - uses: azure/webapps-deploy@v2
        with:
          app-name: 'myapp'
          images: 'bankapphenn.azurecr.io/myapp:${{ github.sha }}'
    
      - name: Azure logout
        run: |
          az logout


    
